### ISSUE TITLE
django-form-designer does not work with Python 2.4.x

### ISSUE THREAD

**Issue by jazzcat-zz** [samluescher/django-form-designer#7]
There are many places in the code with syntax such as this:

'form_designer/js/lib/jquery.js' if not hasattr....

Python 2.4.x does not support this type of syntax.

This will be a problem, because many folks running Django are running under RHEL5; and RHEL5's system Python is 2.4.x.  I'll go through this tonight, make changes, and submit a patch.

**Comment by jazzcat-zz** [comment]
Can I email a patch or do I need some kind of committer status - not sure how git works.

**Comment by samluescher** [comment]
Hi, thank you for your help. I used this shorthand because I thought it looked neater but apparently I made an uninformed choice.
The usual way (and the easiest one, for the project owner) would be you forking the project on GitHub, then cloning your fork, making changes, then submitting a pull request with the button near the top of the page. Explained here: http://help.github.com/forking/

A simple patch would help, too, but forking is better.
